# Generated by Django 2.2.3 on 2019-10-14 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_test',
            new_name='post_text',
        ),
    ]
